version: "3.9"

services:
  laravel:
    container_name: ksiegarnia-app
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - ksiegarnia-volume:/var/www/html/storage
    networks:
      - ksiegarnia-network

  database:
    container_name: ksiegarnia-db
    image: mariadb:latest
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ksiegarnia-db-volume:/var/lib/mysql
    networks:
      - ksiegarnia-network

volumes:
  ksiegarnia-db-volume:
  ksiegarnia-volume:

networks:
  ksiegarnia-network:
    driver: bridge